### ISSUE TITLE
nộp bài

### ISSUE THREAD

**Issue by hoaithu1168** [UET-INT2204-11-fall-18/lab01-hoaithu1168#1]
Họ tên: Nguyễn Hoài Thu
MSSV: 16021168
Email: hoaithub1k54@gmail.com
Nhóm 1

**Comment by tuantmtb** [comment]
@hoaithu1168 em chưa push code lên
Em kiểm tra lại nhé https://github.com/UET-INT2204-11-fall-18/lab01-hoaithu1168

**Comment by tuantmtb** [comment]
Em xem lại nhé, em chưa đẩy code lên

**Comment by hoaithu1168** [comment]
em vừa push rồi ạ
lúc trước em quên mất, mới commit mà chưa push :))))

**Comment by tuantmtb** [comment]
ok em. Em lưu ý file là .java chứ k phải .java.txt nhé

**Comment by hoaithu1168** [comment]
vâng, em vừa chỉnh lại rồi ạ
